import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google"; // Import Poppins and Inter fonts
import "./globals.css";

// Configure the Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Specify the character subsets
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"], // Add required font weights
  variable: "--font-poppins", // CSS variable for Poppins
});

// Configure the Inter font
const inter = Inter({
  subsets: ["latin"], // Specify the character subsets
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Add required font weights
  variable: "--font-inter", // CSS variable for Inter
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`} // Apply both fonts
      >
        {children}
      </body>
    </html>
  );
}
